#!/usr/bin/env node
/**
 * Syncs versions and resolves workspace:* protocol references in a dist package.json.
 *
 * Per-project script designed to be called as an Nx target:
 *   node scripts/sync-dist.mjs <projectName>
 *
 * Steps:
 * 1. Copies `version` from source package.json to dist package.json
 * 2. Resolves workspace:* protocol references to actual version numbers
 * 3. Patches subpath exports from the distExports field
 * 4. Patches bin entries from the distBin field
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, resolve } from 'path';

const projectName = process.argv[2];
if (!projectName) {
  console.error('Usage: node scripts/sync-dist.mjs <projectName>');
  process.exit(1);
}

const workspaceRoot = process.cwd();
const distPkgPath = resolve(workspaceRoot, 'dist/packages', projectName, 'package.json');
const srcPackagesDir = resolve(workspaceRoot, 'packages');

if (!existsSync(distPkgPath)) {
  console.error(`Dist package.json not found: ${distPkgPath}`);
  console.error('Run build first.');
  process.exit(1);
}

const distPkg = JSON.parse(readFileSync(distPkgPath, 'utf-8'));
let modified = false;

// Find source package dir by matching package name
function findSourceDir(pkgName) {
  for (const dir of readdirSync(srcPackagesDir, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue;
    const srcPath = join(srcPackagesDir, dir.name, 'package.json');
    if (!existsSync(srcPath)) continue;
    try {
      const srcPkg = JSON.parse(readFileSync(srcPath, 'utf-8'));
      if (srcPkg.name === pkgName) return { dir: dir.name, pkg: srcPkg };
    } catch {
      // skip
    }
  }
  return null;
}

// 1. Sync version from source
const source = findSourceDir(distPkg.name);
if (source && source.pkg.version && distPkg.version !== source.pkg.version) {
  console.log(`  version: ${distPkg.version} -> ${source.pkg.version}`);
  distPkg.version = source.pkg.version;
  modified = true;
}

// 2. Resolve workspace:* references
const depTypes = ['dependencies', 'devDependencies', 'peerDependencies'];
for (const depType of depTypes) {
  const deps = distPkg[depType];
  if (!deps) continue;

  for (const [name, version] of Object.entries(deps)) {
    if (typeof version === 'string' && version.startsWith('workspace:')) {
      const dep = findSourceDir(name);
      if (dep && dep.pkg.version) {
        const modifier = version.slice('workspace:'.length);
        deps[name] = modifier === '*' ? dep.pkg.version : `${modifier}${dep.pkg.version}`;
        console.log(`  ${depType}.${name}: ${version} -> ${deps[name]}`);
        modified = true;
      } else {
        console.warn(`  Warning: Could not resolve ${name} (not found in workspace)`);
      }
    }
  }
}

// 3. Rebuild exports field from Nx-generated metadata + distExports
// Source-level `exports` (used for workspace TS resolution) must not leak into dist.
if (source) {
  const hasDistExports =
    source.pkg.distExports && typeof source.pkg.distExports === 'object';
  const hasSourceExports =
    source.pkg.exports && typeof source.pkg.exports === 'object';

  if (hasDistExports || hasSourceExports) {
    // Start fresh: keep only the Nx-generated "." and "./package.json" entries
    const mainExport = distPkg.exports?.['.'];
    const newExports = {};

    if (typeof mainExport === 'object' && mainExport !== null) {
      // Nx-generated "." with types/import/default — keep as-is
      newExports['.'] = mainExport;
    } else if (distPkg.types && distPkg.module) {
      // Rebuild "." from top-level fields generated by Nx
      newExports['.'] = {
        types: distPkg.types,
        import: distPkg.module,
        default: distPkg.module,
      };
    }

    // Add distExports subpaths
    if (hasDistExports) {
      for (const [subpath, jsPath] of Object.entries(source.pkg.distExports)) {
        const dtsPath = jsPath.replace(/\.js$/, '.d.ts');
        newExports[subpath] = {
          types: dtsPath,
          import: jsPath,
          default: jsPath,
        };
        console.log(`  exports["${subpath}"]: patched -> ${jsPath}`);
      }
    }

    newExports['./package.json'] = './package.json';
    distPkg.exports = newExports;
    modified = true;
  }
}

// 4. Patch bin entries from distBin
if (source && source.pkg.distBin && typeof source.pkg.distBin === 'object') {
  distPkg.bin = source.pkg.distBin;
  for (const [name, binPath] of Object.entries(source.pkg.distBin)) {
    console.log(`  bin["${name}"]: patched -> ${binPath}`);
  }
  modified = true;
}

// Strip dist-only fields from dist package.json
if (distPkg.distExports) {
  delete distPkg.distExports;
  modified = true;
}
if (distPkg.distBin) {
  delete distPkg.distBin;
  modified = true;
}

if (modified) {
  writeFileSync(distPkgPath, JSON.stringify(distPkg, null, 2) + '\n');
  console.log(`  ${projectName}: synced`);
} else {
  console.log(`  ${projectName}: no changes needed`);
}
